version: '3'
services:

  app:
    # build: .
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      # - .:/app
      - ./app:/app/app
      - ./sql:/app/sql
      - ./data:/app/data
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: mendel
      POSTGRES_USER: mendel
      POSTGRES_PASSWORD: zPO5uhF4VDjm
    command: ["python", "app/main.py", "--interval", "once", "--time", "14:15"]

  # app:
  #     image: mendel/app
  #     depends_on:
  #       - db
  #     ports:
  #       - "8000:8000"

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: mendel
      POSTGRES_USER: mendel
      POSTGRES_PASSWORD: zPO5uhF4VDjm # mendel_mendel
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: