version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./sql:/app/sql
      - ./data:/app/data

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: mendel
      POSTGRES_USER: mendel
      POSTGRES_PASSWORD: zPO5uhF4VDjm # mendel_mendel
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: